#	UGR Transparente. Sitio Web de la Universidad de Granada de acceso a Datos Abiertos.
#	Copyright (C) 2015 Mario Heredia Moreno
#
#	This file is part of UGR Transparente.
#
#	UGR Transparente is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	UGR Transparente is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program. If not, see <http://www.gnu.org/licenses/>.


---
- hosts: transparente-servidor
  sudo: yes
  remote_user: {user}
  # ¡OJO! Cambiar donde ponga {user} por el usuario de la máquina remota donde estemos realizando la instalación
  tasks:

    - name: Instalamos git
      apt: name=git state=present

    - name: Instalamos nvm para node
      shell: >
            curl https://raw.githubusercontent.com/creationix/nvm/v0.24.0/install.sh | sh
            creates=/home/{user}/.nvm/nvm.sh

    - name: Instalamos node
      shell: >
            /bin/bash -c "source ~/.nvm/nvm.sh && nvm install 0.10 && nvm alias default 0.10"
            creates=/home/{user}/.nvm/alias

    - name: Si la instalación es sobre Ubuntu 14.10, solucionamos error de entorno de node
      shell: ln -s /usr/bin/nodejs /usr/bin/node
      ignore_errors: yes

    - name: Instalamos npm
      apt: name=npm state=present

    - name: Instalamos forever para node.js
      npm: name=forever global=yes state=present

    - name: Creamos directorio para despliegue
      file: path=/home/{user}/ugr-transparente-servidor/ state=directory

    - name: Descargamos la aplicación de github
      action: git repo=https://github.com/oslugr/ugr-transparente-servidor.git dest=/home/{user}/ugr-transparente-servidor
      tags: deploy

    - name: Instalamos dependencias
      command: npm install chdir=/home/{user}/ugr-transparente-servidor

    - name: Creamos servicio de inicio
      template: src=transparente-ugr.conf dest=/etc/init/transparente-ugr.conf owner=root group=root mode=0644

    - name: Lanzamos aplicación
      command: npm start chdir=/home/{user}/ugr-transparente-servidor
